export interface FailureCase {
  id: string;
  name: string;
  industry: string;
  yearFounded: number;
  yearDied: number;
  archetype:
    | "premium-bet"
    | "founder-ego"
    | "wrong-timing"
    | "no-pmf"
    | "burn-rate"
    | "regulatory"
    | "execution"
    | "competition";
  primaryCause: string;
  capitalRaised: string;
  oneLiner: string;
  tags: string[];
}

export const FAILURE_DATABASE: FailureCase[] = [
  {
    id: "quibi",
    name: "Quibi",
    industry: "Streaming",
    yearFounded: 2018,
    yearDied: 2020,
    archetype: "wrong-timing",
    primaryCause: "Launched a mobile-only short-form streaming service during a pandemic when people were stuck at home with big screens",
    capitalRaised: "$1.75B",
    oneLiner: "Wrong format, wrong timing — $1.75B gone in 6 months",
    tags: ["streaming", "mobile", "short-form", "timing", "subscription", "celebrity-founded"],
  },
  {
    id: "theranos",
    name: "Theranos",
    industry: "Healthcare",
    yearFounded: 2003,
    yearDied: 2018,
    archetype: "founder-ego",
    primaryCause: "Systematic fraud — technology never worked but founder kept raising capital and lying to investors and patients",
    capitalRaised: "$700M",
    oneLiner: "Blood-testing tech that never worked, $9B valuation built on fraud",
    tags: ["healthcare", "fraud", "founder-cult", "biotech", "regulatory", "deception"],
  },
  {
    id: "google-plus",
    name: "Google+",
    industry: "Social Media",
    yearFounded: 2011,
    yearDied: 2019,
    archetype: "competition",
    primaryCause: "Late to social, forced adoption couldn't overcome Facebook's network effects",
    capitalRaised: "Internal (Google)",
    oneLiner: "Late to social, privacy scandal, engagement never took off",
    tags: ["social", "big-tech", "network-effects", "forced-adoption", "competition"],
  },
  {
    id: "moviepass",
    name: "MoviePass",
    industry: "Entertainment",
    yearFounded: 2011,
    yearDied: 2019,
    archetype: "burn-rate",
    primaryCause: "Unsustainable $9.95/month all-you-can-watch model burned cash faster than revenue could ever cover",
    capitalRaised: "$150M+",
    oneLiner: "Unsustainable $9.95 model burned $150M in 18 months",
    tags: ["entertainment", "subscription", "unit-economics", "burn-rate", "hype"],
  },
  {
    id: "juicero",
    name: "Juicero",
    industry: "Consumer Hardware",
    yearFounded: 2013,
    yearDied: 2017,
    archetype: "premium-bet",
    primaryCause: "$400 WiFi-connected juicer that squeezed bags you could squeeze by hand — solution in search of a problem",
    capitalRaised: "$120M",
    oneLiner: "$400 WiFi juicer that could be replaced by human hands",
    tags: ["hardware", "iot", "premium", "overengineered", "silicon-valley-delusion"],
  },
  {
    id: "wework",
    name: "WeWork",
    industry: "Real Estate",
    yearFounded: 2010,
    yearDied: 2023,
    archetype: "founder-ego",
    primaryCause: "Charismatic founder inflated valuation through self-dealing, eccentric governance, and negative unit economics dressed as tech",
    capitalRaised: "$11B+",
    oneLiner: "Leadership chaos, $47B valuation to bankruptcy in 6 weeks",
    tags: ["real-estate", "founder-cult", "governance", "valuation-bubble", "ipo-fail"],
  },
  {
    id: "vine",
    name: "Vine",
    industry: "Social Media",
    yearFounded: 2012,
    yearDied: 2016,
    archetype: "execution",
    primaryCause: "Twitter neglected the product, failed to monetize, and let creators flee to Instagram and YouTube",
    capitalRaised: "Acquired by Twitter",
    oneLiner: "Twitter cut the cord before short-form video went global",
    tags: ["social", "short-form", "video", "neglect", "acquisition-fail"],
  },
  {
    id: "clubhouse",
    name: "Clubhouse",
    industry: "Social Media",
    yearFounded: 2020,
    yearDied: 2023,
    archetype: "no-pmf",
    primaryCause: "Audio-only hype cycle with no lasting moat — engagement collapsed once pandemic exclusivity faded",
    capitalRaised: "$110M",
    oneLiner: "Audio-only hype cycle, no lasting moat, engagement evaporated",
    tags: ["social", "audio", "hype-cycle", "pandemic-product", "exclusive"],
  },
  {
    id: "pets-com",
    name: "Pets.com",
    industry: "E-Commerce",
    yearFounded: 1998,
    yearDied: 2000,
    archetype: "burn-rate",
    primaryCause: "Spent millions on Super Bowl ads and free shipping while selling pet food at a loss — classic dot-com bubble",
    capitalRaised: "$110M (IPO)",
    oneLiner: "Iconic dot-com flameout — sock puppet mascot, zero margins",
    tags: ["e-commerce", "dot-com", "burn-rate", "ad-spend", "negative-margins"],
  },
  {
    id: "webvan",
    name: "Webvan",
    industry: "Grocery Delivery",
    yearFounded: 1996,
    yearDied: 2001,
    archetype: "burn-rate",
    primaryCause: "Built $1B in automated warehouses before proving demand existed — scale-before-product-market-fit",
    capitalRaised: "$1.2B",
    oneLiner: "Built $1B warehouses before proving anyone wanted grocery delivery",
    tags: ["delivery", "grocery", "infrastructure-overbuild", "scale-too-fast", "dot-com"],
  },
  {
    id: "better-place",
    name: "Better Place",
    industry: "Automotive / Clean Energy",
    yearFounded: 2007,
    yearDied: 2013,
    archetype: "premium-bet",
    primaryCause: "Built a global battery-swap infrastructure nobody wanted — car makers wouldn't adopt the standard",
    capitalRaised: "$850M",
    oneLiner: "Battery-swap stations nobody needed — $850M for an unused network",
    tags: ["automotive", "infrastructure", "clean-energy", "standard-wars", "overbuild"],
  },
  {
    id: "solyndra",
    name: "Solyndra",
    industry: "Clean Energy",
    yearFounded: 2005,
    yearDied: 2011,
    archetype: "competition",
    primaryCause: "Cylindrical solar panels couldn't compete as Chinese silicon prices collapsed 80%",
    capitalRaised: "$1B+ (incl. $535M US gov loan)",
    oneLiner: "Cylindrical solar tubes crushed by plummeting Chinese panel prices",
    tags: ["clean-energy", "manufacturing", "government-backed", "china-competition", "commodity"],
  },
  {
    id: "kodak",
    name: "Kodak",
    industry: "Photography / Imaging",
    yearFounded: 1888,
    yearDied: 2012,
    archetype: "wrong-timing",
    primaryCause: "Invented the digital camera in 1975 but suppressed it to protect film revenue — missed the transition they created",
    capitalRaised: "Public company",
    oneLiner: "Invented digital photography then buried it to protect film",
    tags: ["photography", "disruption", "innovator-dilemma", "film", "digital"],
  },
  {
    id: "blackberry",
    name: "BlackBerry",
    industry: "Mobile / Technology",
    yearFounded: 1984,
    yearDied: 2022,
    archetype: "competition",
    primaryCause: "Dismissed touchscreens and consumer apps, clung to physical keyboard while iPhone redefined the market",
    capitalRaised: "Public company",
    oneLiner: "Physical keyboard loyalism while the world went touchscreen",
    tags: ["mobile", "enterprise", "keyboard", "touchscreen-delay", "app-ecosystem"],
  },
  {
    id: "yahoo",
    name: "Yahoo",
    industry: "Internet / Search",
    yearFounded: 1994,
    yearDied: 2017,
    archetype: "execution",
    primaryCause: "Passed on buying Google for $5B, Facebook for $1B, and Netflix — leadership revolving door with no product vision",
    capitalRaised: "Public company",
    oneLiner: "Passed on Google, Facebook, and Netflix — leadership chaos killed the portal",
    tags: ["search", "portal", "missed-acquisitions", "leadership-revolving-door", "vision-gap"],
  },
  {
    id: "friendster",
    name: "Friendster",
    industry: "Social Media",
    yearFounded: 2002,
    yearDied: 2011,
    archetype: "execution",
    primaryCause: "Technical infrastructure couldn't scale — pages took 40 seconds to load while MySpace and Facebook ran fast",
    capitalRaised: "$50M",
    oneLiner: "First major social network, crushed by its own 40-second page loads",
    tags: ["social", "infrastructure", "scaling", "first-mover-fail", "technical-debt"],
  },
  {
    id: "myspace",
    name: "MySpace",
    industry: "Social Media",
    yearFounded: 2003,
    yearDied: 2011,
    archetype: "competition",
    primaryCause: "News Corp turned a cultural phenomenon into an ad-choked mess while Facebook offered clean design and real identity",
    capitalRaised: "Acquired by News Corp ($580M)",
    oneLiner: "Cultural giant crushed by ads and clutter while Facebook offered clarity",
    tags: ["social", "media-acquisition", "ad-overload", "user-experience", "competition"],
  },
  {
    id: "sears",
    name: "Sears",
    industry: "Retail",
    yearFounded: 1892,
    yearDied: 2018,
    archetype: "execution",
    primaryCause: "Hedge fund CEO extracted real estate value while neglecting stores — catalog pioneer missed e-commerce entirely",
    capitalRaised: "Public company",
    oneLiner: "Invented mail-order retail, missed the internet, asset-stripped by its own CEO",
    tags: ["retail", "catalog", "e-commerce-miss", "hedge-fund", "asset-stripping"],
  },
  {
    id: "borders",
    name: "Borders",
    industry: "Retail / Books",
    yearFounded: 1971,
    yearDied: 2011,
    archetype: "wrong-timing",
    primaryCause: "Outsourced online sales to Amazon instead of building its own — literally handed its digital future to the killer",
    capitalRaised: "Public company",
    oneLiner: "Outsourced its website to Amazon — literally funded its own killer",
    tags: ["retail", "books", "outsourcing", "e-commerce-miss", "amazon"],
  },
  {
    id: "blockbuster",
    name: "Blockbuster",
    industry: "Entertainment / Rental",
    yearFounded: 1985,
    yearDied: 2010,
    archetype: "wrong-timing",
    primaryCause: "Passed on buying Netflix for $50M, clung to late fees while streaming ate the market",
    capitalRaised: "Public company",
    oneLiner: "Passed on Netflix for $50M — late fees were more important than the future",
    tags: ["entertainment", "rental", "streaming", "missed-acquisition", "legacy-revenue"],
  },
  {
    id: "blue-apron",
    name: "Blue Apron",
    industry: "Food / Subscription",
    yearFounded: 2012,
    yearDied: 2023,
    archetype: "burn-rate",
    primaryCause: "Churn exceeded growth — marketing spend to acquire customers cost more than lifetime value of each subscriber",
    capitalRaised: "$200M (IPO)",
    oneLiner: "Meal-kit churn devoured its own growth — LTV never covered CAC",
    tags: ["food", "subscription", "churn", "unit-economics", "cac-ltv"],
  },
  {
    id: "color-labs",
    name: "Color Labs",
    industry: "Photo Sharing / Social",
    yearFounded: 2010,
    yearDied: 2012,
    archetype: "no-pmf",
    primaryCause: "Raised $41M pre-launch for a proximity-based photo app nobody understood — classic overfunded, under-validated",
    capitalRaised: "$41M",
    oneLiner: "Raised $41M before launch for an app nobody could explain",
    tags: ["social", "photo", "overfunded", "no-validation", "proximity"],
  },
  {
    id: "homejoy",
    name: "Homejoy",
    industry: "On-Demand Services",
    yearFounded: 2012,
    yearDied: 2015,
    archetype: "execution",
    primaryCause: "Classified workers as contractors but faced lawsuits — margins collapsed when forced to reclassify",
    capitalRaised: "$40M",
    oneLiner: "Home cleaning platform crushed by worker classification lawsuits",
    tags: ["on-demand", "gig-economy", "contractor-misclassification", "legal", "marketplace"],
  },
  {
    id: "shyp",
    name: "Shyp",
    industry: "Logistics / On-Demand",
    yearFounded: 2013,
    yearDied: 2018,
    archetype: "burn-rate",
    primaryCause: "Sent a courier to pick up one package — unit economics made zero sense without density",
    capitalRaised: "$63M",
    oneLiner: "On-demand courier for single packages — unit economics never worked",
    tags: ["logistics", "on-demand", "unit-economics", "density-problem", "burn-rate"],
  },
  {
    id: "magic-leap",
    name: "Magic Leap",
    industry: "AR / Hardware",
    yearFounded: 2010,
    yearDied: 2022,
    archetype: "premium-bet",
    primaryCause: "Raised $2.3B on cinematic concept videos that the actual headset couldn't match — consumer product flopped",
    capitalRaised: "$2.3B",
    oneLiner: "$2.3B raised on cinematic AR demos the actual headset never delivered",
    tags: ["ar", "hardware", "hype", "concept-vs-reality", "overpromised"],
  },
  {
    id: "casper",
    name: "Casper",
    industry: "D2C / Sleep",
    yearFounded: 2014,
    yearDied: 2022,
    archetype: "competition",
    primaryCause: "Mattress-in-a-box had no moat — hundreds of clones and incumbents fought back, IPO priced at half target",
    capitalRaised: "$340M (IPO)",
    oneLiner: "Mattress-in-a-box with zero moat — 200 clones appeared overnight",
    tags: ["d2c", "mattress", "no-moat", "clone-competition", "ipo-disappoint"],
  },
  {
    id: "jawbone",
    name: "Jawbone",
    industry: "Consumer Electronics / Wearables",
    yearFounded: 1999,
    yearDied: 2017,
    archetype: "competition",
    primaryCause: "Pioneered fitness trackers but lost to FitBit on price and Apple Watch on quality — years of pivots couldn't save it",
    capitalRaised: "$1B+",
    oneLiner: "Fitness tracker pioneer outpaced by FitBit's price and Apple's brand",
    tags: ["wearables", "hardware", "competition", "pivots", "pioneer-penalty"],
  },
  {
    id: "beepi",
    name: "Beepi",
    industry: "Automotive / Marketplace",
    yearFounded: 2013,
    yearDied: 2017,
    archetype: "burn-rate",
    primaryCause: "Peer-to-peer used car marketplace burned cash on inspections and guarantees that couldn't scale profitably",
    capitalRaised: "$150M",
    oneLiner: "P2P used car market with inspection costs that devoured every transaction",
    tags: ["automotive", "marketplace", "unit-economics", "inspection-costs", "p2p"],
  },
  {
    id: "munchery",
    name: "Munchery",
    industry: "Food Delivery",
    yearFounded: 2010,
    yearDied: 2019,
    archetype: "burn-rate",
    primaryCause: "Meal delivery with cold-chain logistics and chef salaries — subscription food never hit profitable unit economics",
    capitalRaised: "$120M",
    oneLiner: "Chef-prepared meal delivery with cold-chain costs that ate every margin",
    tags: ["food-delivery", "subscription", "logistics", "cold-chain", "unit-economics"],
  },
  {
    id: "doppler-labs",
    name: "Doppler Labs",
    industry: "Consumer Hardware / Audio",
    yearFounded: 2013,
    yearDied: 2018,
    archetype: "premium-bet",
    primaryCause: "Smart earplugs were a niche product marketed to mainstream — expensive hardware with limited use case couldn't find scale",
    capitalRaised: "$50M",
    oneLiner: "Smart earplugs too niche for mainstream — hardware without a market",
    tags: ["hardware", "audio", "niche-product", "premium", "mainstream-gap"],
  },
];

const DEMO_IDS = [
  "quibi", "theranos", "google-plus", "moviepass", "juicero", "wework",
  "vine", "clubhouse", "pets-com", "webvan", "blockbuster", "kodak",
];

export function getDemoCases(): FailureCase[] {
  return DEMO_IDS.map((id) => FAILURE_DATABASE.find((c) => c.id === id)!).filter(Boolean);
}

export function findSimilarFailures(
  archetype: string,
  tags: string[],
  excludeId?: string
): FailureCase[] {
  const candidates = FAILURE_DATABASE.filter((c) => c.id !== excludeId);

  const scored = candidates.map((c) => {
    let score = 0;
    // Archetype match is weighted heavily
    if (c.archetype === archetype) score += 10;
    // Tag overlap — each matching tag adds 1 point
    for (const tag of tags) {
      if (c.tags.includes(tag)) score += 1;
    }
    return { case: c, score };
  });

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, 3).map((s) => s.case);
}
